# Generated by Django 5.0.4 on 2024-04-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bmi_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='users_workouts',
            field=models.ManyToManyField(null=True, to='main.workout'),
        ),
    ]
